Load the dataset

In [2]:
import pandas as pd
import os

path = os.path.join('..','results','dataset_with_noNA.csv')
factors_df = pd.read_csv(path).drop('Date', axis=1)

factors_df

,PERD_GR,TR1_Corr_N,TR1_Pot_att,TR1_cosFi,TR2_Corr_N,TR2_Pot_att,TR2_cosFi,TR3_Corr_N,TR3_Pot_att,TR3_cosFi
0,0.325737,-2.141435,-1.511963,0.257900,-2.441477,-2.385681,-2.486445,2.486754,2.639974,2.497832
1,-0.055789,-0.447794,-0.837576,0.085235,-2.441477,-2.385681,-2.486445,2.402577,2.513033,2.462639
2,0.230586,-1.294615,-1.039892,0.310450,-2.441477,-2.385681,-2.486445,2.276312,2.534747,2.501964
3,0.073282,-0.730068,-1.606377,0.248516,-2.441477,-2.385681,-2.486445,2.297356,2.568152,2.494586
4,0.261105,-1.953253,-1.417549,0.216610,-2.441477,-2.385681,-2.486445,2.465709,2.586525,2.486839
...,...,...,...,...,...,...,...,...,...,...
13111,0.107956,1.716303,-0.837576,0.042069,0.600657,0.935135,0.453502,-0.396297,-0.399918,-0.400139
13112,0.087578,1.528121,-0.628516,0.152799,0.600657,0.894755,0.435150,-0.396297,-0.399918,-0.400139
13113,0.111889,1.528121,0.005408,0.141539,0.546333,0.828533,0.448840,-0.396297,-0.399918,-0.400139
13114,0.179459,2.845398,0.005408,0.186582,0.781736,1.027200,0.436852,-0.396297,-0.399918,-0.400139
13115,0.166231,3.504036,0.855135,-0.001098,0.817952,0.816688,0.412284,-0.396297,-0.399918,-0.400139

Perform factor analysis

In [13]:
from sklearn.decomposition import FactorAnalysis

fa = FactorAnalysis(n_components=3, random_state=0)
fa.fit(factors_df)

# The factor loadings (how much each variable contributes to each factor)

factor_scores = fa.transform(factors_df)

factor_loadings = pd.DataFrame(fa.components_, columns=factors_df.columns)

factor_loadings

,PERD_GR,TR1_Corr_N,TR1_Pot_att,TR1_cosFi,TR2_Corr_N,TR2_Pot_att,TR2_cosFi,TR3_Corr_N,TR3_Pot_att,TR3_cosFi
0,0.035767,-0.303027,-0.468943,0.025638,-0.981265,-0.961132,-0.995336,0.989300,0.997744,0.998703
1,-0.164338,-0.454788,0.588268,-0.199744,-0.179733,-0.267125,-0.032308,-0.026381,-0.026801,-0.026331
2,-0.798112,0.144571,-0.258292,-0.660763,-0.013584,0.019117,-0.053149,-0.004932,-0.001457,-0.002100

3D plot clustering results in the fact

In [14]:
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from sklearn.cluster import KMeans

factor_scores

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot of the factor scores, colored by cluster

scatter = ax.scatter(factor_scores[:, 0], factor_scores[:, 1], factor_scores[:, 2], c=clusters, cmap='viridis')

# Adding labels
ax.set_xlabel('Factor 1')
ax.set_ylabel('Factor 2')
ax.set_zlabel('Factor 3')
ax.set_title('3D Plot of Clusters in Factor Space')

# Adding a color bar
plt.colorbar(scatter)
plt.show()

array([[ 2.51690709, -0.12520073, -0.2105942 ],
       [ 2.47483143,  0.05581525,  0.09575367],
       [ 2.50541401, -0.07052953, -0.18454667],
       ...,
       [-0.43095738, -1.21749829,  0.23591469],
       [-0.45178986, -2.00041712,  0.31412351],
       [-0.44261101, -1.56560292,  0.0745023 ]])